BibliotecaWebApplication/BibliotecaWebApplication/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Libros
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            var libros = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .ToListAsync();
            return View(libros);
        }

        // GET: Libros/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libros/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewBag.Autores = _context.Autores.ToList();
            return View();
        }

        // POST: Libros/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,PortadaUrl,ContraportadaUrl")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            //if (ModelState.IsValid)
            {
                var publicacion = new Publicacion
                {
                    PublicacionId = Guid.NewGuid()
                };

                _context.Publicaciones.Add(publicacion);
                await _context.SaveChangesAsync();

                libro.PublicacionId = publicacion.PublicacionId;
                libro.LibroId = Guid.NewGuid();
             
                _context.Add(libro);
                await _context.SaveChangesAsync();

                if (selectedAutores != null)
                {
                    foreach (var autorId in selectedAutores)
                    {
                        var autorLibro = new AutorLibro
                        {
                            AutorId = autorId,
                            LibroId = libro.LibroId
                        };
                        _context.AutorLibros.Add(autorLibro);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            return View(libro);
        }



        // GET: Libros/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.Publicacion)
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);

            if (libro == null)
            {
                return NotFound();
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = libro.AutorLibros.Select(al => al.AutorId).ToList() ?? new List<Guid>();

            return View(libro);
        }

        // POST: Libros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            if (id != libro.LibroId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var libroFromDb = await _context.Libros
                        .Include(l => l.Publicacion)
                        .FirstOrDefaultAsync(l => l.LibroId == id);

                    if (libroFromDb == null)
                    {
                        return NotFound();
                    }

                    libroFromDb.ISBN = libro.ISBN;
                    libroFromDb.Titulo = libro.Titulo;
                    libroFromDb.NumeroPaginas = libro.NumeroPaginas;
                    libroFromDb.Formato = libro.Formato;

                    

                    _context.Update(libroFromDb);
                    await _context.SaveChangesAsync();

                    var existingAutorLibros = _context.AutorLibros.Where(al => al.LibroId == id);
                    _context.AutorLibros.RemoveRange(existingAutorLibros);

                    if (selectedAutores != null && selectedAutores.Any())
                    {
                        foreach (var autorId in selectedAutores)
                        {
                            var autorLibro = new AutorLibro
                            {
                                AutorId = autorId,
                                LibroId = libro.LibroId
                            };
                            _context.AutorLibros.Add(autorLibro);
                        }
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = selectedAutores != null ? selectedAutores.ToList() : new List<Guid>();
            return View(libro);
        }


        private bool LibroExists(Guid id)
        {
            return _context.Libros.Any(e => e.LibroId == id);
        }



        // GET: Libros/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                .Include(l => l.Publicacion) // Incluye la Publicacion asociada
                .FirstOrDefaultAsync(l => l.LibroId == id);

            if (libro != null)
            {
                // Eliminar relaciones en AutorLibro
                _context.AutorLibros.RemoveRange(libro.AutorLibros);

                // Eliminar la publicacion asociada
                if (libro.Publicacion != null)
                {
                    _context.Publicaciones.Remove(libro.Publicacion);
                }

                // Eliminar el libro
                _context.Libros.Remove(libro);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/RolesController.cs
using BibliotecaWebApplication.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BibliotecaWebApplication.Controllers
{
    [Authorize(Roles = "Root, Administrador")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        // GET: RolesConroller 
        public async Task<ActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        // GET: RolesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = model.Name };
                IdentityResult result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return View(model);
        }

        // GET: RolesController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            RoleViewModel model = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(model);
        }

        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    return NotFound();
                }
                role.Name = model.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        //// POST: RolesController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Delete(string id)
        //{
        //    var role = await _roleManager.FindByIdAsync(id);
        //    if (role != null)
        //    {
        //        var result = await _roleManager.DeleteAsync(role);
        //        if (result.Succeeded)
        //        {
        //            return RedirectToAction("Index");
        //        }
        //        foreach (var error in result.Errors)
        //        {
        //            ModelState.AddModelError("", error.Description);
        //        }
        //    }
        //    return View("Index");
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Root")]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", new { deletionSuccess = true });
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("Index");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BibliotecaWebApplication.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    [Authorize(Roles = "Root, Administrador")]
    public class UserRolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserRolesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: RolesConroller 
        public async Task<ActionResult> Index()
        {
            var users =  _userManager.Users.ToList();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (var user in users) { 
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
            
        }

        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        // GET: UserRolesController/Manage
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;

            var model = new List<ManageUserRolesViewModel>();

            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }
                else
                {
                    userRolesViewModel.IsSelected = false;
                }

                model.Add(userRolesViewModel);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            // Encuentra al usuario basado en el userId proporcionado
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View("NotFound");
            }

            // Obtén los roles actuales asociados al usuario
            var currentRoles = await _userManager.GetRolesAsync(user);

            // Filtro para obtener los roles que necesitan ser agregados
            var rolesToAdd = model.Where(x => x.IsSelected && !currentRoles.Contains(x.RoleName)).Select(x => x.RoleName);

            // Filtro para obtener los roles que necesitan ser removidos
            var rolesToRemove = currentRoles.Where(role => !model.Any(x => x.RoleName == role && x.IsSelected));

            // Resultado de remover los roles no deseados
            var removeResult = await _userManager.RemoveFromRolesAsync(user, rolesToRemove);
            if (!removeResult.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }

            // Resultado de agregar los nuevos roles seleccionados
            var addResult = await _userManager.AddToRolesAsync(user, rolesToAdd);
            if (!addResult.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }

            // Redirige al índice si todo es exitoso
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "Acceso Denegado";
}


<h1>Acceso Denegado</h1>
<p>No tienes permisos para acceder a esta página.</p>

<a asp-controller="Home" asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>

BibliotecaWebApplication/BibliotecaWebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca Sabiduría</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #343a40;
            color: #f8f9fa;
        }

        .navbar {
            background-color: #343a40;
        }

        .navbar-brand,
        .nav-link {
            color: #f8f9fa !important;
        }

        .nav-link {
            margin-right: 15px;
        }

            .nav-link:hover {
                color: #adb5bd !important;
            }

        .dropdown-menu {
            background-color: #343a40;
            border: none;
        }

        .dropdown-item {
            color: #f8f9fa;
        }

            .dropdown-item:hover {
                background-color: #495057;
            }

        footer {
            background-color: #212529;
            color: #f8f9fa;
            padding: 20px 0;
        }

            footer a {
                color: #adb5bd;
            }

                footer a:hover {
                    color: #f8f9fa;
                }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            border-radius: 20px;
            padding: 10px 20px;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

        .container {
            margin-top: 30px;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Biblioteca Sabiduría</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        @* Dropdown menus for authenticated users with specific roles *@
                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && (await UserManager.IsInRoleAsync(user, "Bibliotecario") || await UserManager.IsInRoleAsync(user, "Administrador")))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Libros
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Revistas
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Revistas" asp-action="Index">Revistas</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Estanterias
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Estanterias" asp-action="Index">Estanterias</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Estantes" asp-action="Index">Estantes</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Ejemplares" asp-action="Index">Ejemplares</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Roles y Usuarios
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown4">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="UserRoles" asp-action="Index">Usuarios Roles</a></li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto py-3">
        <div class="container text-center">
            &copy; 2024 - Biblioteca(AlejandroCastro) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>