BibliotecaWebApplication/BibliotecaWebApplication/Models/Libro.cs
using BibliotecaWebApplication.Models;
using System.ComponentModel.DataAnnotations;

namespace BibliotecaWebApplication.Models
{
    public class Libro
    {
        [Key]
        public Guid LibroId { get; set; }
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public string Formato { get; set; }
        public int NumeroPaginas { get; set; }
        // Fk Publicacion
        public Guid? PublicacionId { get; set; }
        public Publicacion Publicacion { get; set; }
      
        public Libro()
        {
            this.LibroId = Guid.NewGuid();
        }

        // Propiedades de navegación
        public ICollection<AutorLibro> AutorLibros { get; set; } = new List<AutorLibro>();
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BibliotecaWebApplication.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/AutoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class AutoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AutoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Autores
        [Authorize(Roles ="Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autores.ToListAsync());
        }

        // GET: Autores/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores
                .Include(a => a.AutorLibros) // Incluye los libros asociados al autor
                .ThenInclude(al => al.Libro) // Incluye los detalles de los libros
                .FirstOrDefaultAsync(m => m.AutorId == id);

            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }


        // GET: Autores/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("AutorId,Nombres,Apellidos,Nacionalidad,FotoUrl")] Autor autor, IFormFile foto)
        {
            //if (ModelState.IsValid)
            {
               

                autor.AutorId = Guid.NewGuid();
                _context.Add(autor);
                await _context.SaveChangesAsync();

                // Detectar si la solicitud es AJAX
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    // Retornar un resultado JSON con los detalles del nuevo autor
                    return Json(new { success = true, autor });
                }

                return RedirectToAction(nameof(Index));
            }

            return View(autor);
        }




        // GET: Autores/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores.FindAsync(id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        // POST: Autores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Autores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("AutorId,Nombres,Apellidos,Nacionalidad,FotoUrl")] Autor autor, IFormFile foto)
        {
            if (id != autor.AutorId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var autorExistente = await _context.Autores.AsNoTracking().FirstOrDefaultAsync(a => a.AutorId == id);

                   

                    _context.Update(autor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorExists(autor.AutorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }



        // GET: Autores/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores
                .FirstOrDefaultAsync(m => m.AutorId == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // POST: Autores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var autor = await _context.Autores.FindAsync(id);
            if (autor != null)
            {
                _context.Autores.Remove(autor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorExists(Guid id)
        {
            return _context.Autores.Any(e => e.AutorId == id);
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Libros
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            var libros = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .ToListAsync();
            return View(libros);
        }

        // GET: Libros/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libros/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewBag.Autores = _context.Autores.ToList();
            return View();
        }

        // POST: Libros/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,PortadaUrl,ContraportadaUrl")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            //if (ModelState.IsValid)
            {
                var publicacion = new Publicacion
                {
                    PublicacionId = Guid.NewGuid()
                };

                _context.Publicaciones.Add(publicacion);
                await _context.SaveChangesAsync();

                libro.PublicacionId = publicacion.PublicacionId;
                libro.LibroId = Guid.NewGuid();
             
                _context.Add(libro);
                await _context.SaveChangesAsync();

                if (selectedAutores != null)
                {
                    foreach (var autorId in selectedAutores)
                    {
                        var autorLibro = new AutorLibro
                        {
                            AutorId = autorId,
                            LibroId = libro.LibroId
                        };
                        _context.AutorLibros.Add(autorLibro);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            return View(libro);
        }



        // GET: Libros/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.Publicacion)
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);

            if (libro == null)
            {
                return NotFound();
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = libro.AutorLibros.Select(al => al.AutorId).ToList() ?? new List<Guid>();

            return View(libro);
        }

        // POST: Libros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            if (id != libro.LibroId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var libroFromDb = await _context.Libros
                        .Include(l => l.Publicacion)
                        .FirstOrDefaultAsync(l => l.LibroId == id);

                    if (libroFromDb == null)
                    {
                        return NotFound();
                    }

                    libroFromDb.ISBN = libro.ISBN;
                    libroFromDb.Titulo = libro.Titulo;
                    libroFromDb.NumeroPaginas = libro.NumeroPaginas;
                    libroFromDb.Formato = libro.Formato;

                    

                    _context.Update(libroFromDb);
                    await _context.SaveChangesAsync();

                    var existingAutorLibros = _context.AutorLibros.Where(al => al.LibroId == id);
                    _context.AutorLibros.RemoveRange(existingAutorLibros);

                    if (selectedAutores != null && selectedAutores.Any())
                    {
                        foreach (var autorId in selectedAutores)
                        {
                            var autorLibro = new AutorLibro
                            {
                                AutorId = autorId,
                                LibroId = libro.LibroId
                            };
                            _context.AutorLibros.Add(autorLibro);
                        }
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = selectedAutores != null ? selectedAutores.ToList() : new List<Guid>();
            return View(libro);
        }


        private bool LibroExists(Guid id)
        {
            return _context.Libros.Any(e => e.LibroId == id);
        }



        // GET: Libros/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                .Include(l => l.Publicacion) // Incluye la Publicacion asociada
                .FirstOrDefaultAsync(l => l.LibroId == id);

            if (libro != null)
            {
                // Eliminar relaciones en AutorLibro
                _context.AutorLibros.RemoveRange(libro.AutorLibros);

                // Eliminar la publicacion asociada
                if (libro.Publicacion != null)
                {
                    _context.Publicaciones.Remove(libro.Publicacion);
                }

                // Eliminar el libro
                _context.Libros.Remove(libro);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Views/Libros/AccessDenied.cshtml
@{
    ViewBag.Title = "Acceso Denegado";
}


<h1>Acceso Denegado</h1>
<p>No tienes permisos para acceder a esta página en la sección de Libros.</p>


<a asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>

BibliotecaWebApplication/BibliotecaWebApplication/Views/Libros/Create.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Crear Libro";
}

<h1>Crear Libro</h1>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Formato" class="control-label"></label>
                <input asp-for="Formato" class="form-control" />
                <span asp-validation-for="Formato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPaginas" class="control-label"></label>
                <input asp-for="NumeroPaginas" class="form-control" />
                <span asp-validation-for="NumeroPaginas" class="text-danger"></span>
            </div>
           

            <h4>Seleccionar Autor(es)</h4>
            <table id="dataTable" class="table">
                <thead>
                    <tr>
                        <th>Seleccionar</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Nacionalidad</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var autor in ViewBag.Autores)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="selectedAutores" value="@autor.AutorId" />
                            </td>
                            <td>@autor.Nombres</td>
                            <td>@autor.Apellidos</td>
                            <td>@autor.Nacionalidad</td>
                        </tr>
                    }
                </tbody>
            </table>
            <button type="button" class="btn btn-create" data-toggle="modal" data-target="#crearAutorModal"><i class="fas fa-save"></i> Crear Autor</button>
            <br />
            <br />
            <div class="form-group">
                <button type="submit" class="btn btn-create"><i class="fas fa-save"></i> Guardar</button>
                <a asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="crearAutorModal" tabindex="-1" role="dialog" aria-labelledby="crearAutorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="crearAutorModalLabel">Crear Autor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="crearAutorForm" asp-controller="Autores" asp-action="Create" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="Nombres">Nombres</label>
                        <input type="text" class="form-control" name="Nombres" required />
                    </div>
                    <div class="form-group">
                        <label for="Apellidos">Apellidos</label>
                        <input type="text" class="form-control" name="Apellidos" required />
                    </div>
                    <div class="form-group">
                        <label for="Nacionalidad">Nacionalidad</label>
                        <input type="text" class="form-control" name="Nacionalidad" required />
                    </div>
                 
                    <br />
                    <button type="submit" class="btn btn-create"><i class="fas fa-save"></i> Guardar</button>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "lengthMenu": "Mostrar _MENU_ entradas por página",
                    "zeroRecords": "No se encontraron resultados",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando 0 a 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });

        $(document).ready(function () {
            $('#crearAutorForm').submit(function (e) {
                e.preventDefault(); // Previene el envío tradicional del formulario
                var formData = new FormData(this);
                $.ajax({
                    url: '@Url.Action("Create", "Autores")',
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        if (result.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Éxito',
                                text: 'Autor creado correctamente',
                                showConfirmButton: true
                            }).then((result) => {
                                if (result.isConfirmed) {
                                    // Cerrar el modal
                                    $('#crearAutorModal').modal('hide');
                                    // Recargar la página solo cuando se confirma la alerta
                                    location.reload();
                                }
                            });
                        } else {
                            Swal.fire({
                                icon: 'warning',
                                title: 'Error',
                                text: 'El Autor no se ah creado correctamente',
                                showConfirmButton: true
                            })
                        }
                    }
                });
            });
        });



    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
    

BibliotecaWebApplication/BibliotecaWebApplication/Views/Libros/Delete.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar Libro</h1>

<h3>¿Estás seguro de que deseas eliminar este libro?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>
        <dt class="col-sm-2">
            Autores
        </dt>
        <dd class="col-sm-10">
            @foreach (var autorLibro in Model.AutorLibros)
            {
                <span>@autorLibro.Autor.Nombres @autorLibro.Autor.Apellidos</span>
                <br />
            }
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="LibroId" />
        <button type="submit" class="btn btn-delete"><i class="fas fa-trash-alt"></i> Borrar</button>
        <a asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>
    </form>
</div>

BibliotecaWebApplication/BibliotecaWebApplication/Views/Libros/Details.cshtml
@model BibliotecaWebApplication.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del Libro</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>

        
    </dl>
</div>
<div>
    <h4>Autor(es):</h4>
    @if (Model.AutorLibros.Any())
    {
        <ul class="list-group list-group-flush">
            @foreach (var autorLibro in Model.AutorLibros)
            {
                <li class="list-group-item d-flex align-items-center">
                    <i class="fas fa-user fa-2x text-primary me-2" title="Autor"></i>
                    <span class="fw-semibold">
                        @autorLibro.Autor.Nombres @autorLibro.Autor.Apellidos
                    </span>
                </li>
            }
        </ul>
    }
    else
    {
        <p>Este libro no tiene autores asociados.</p>
    }
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.LibroId" class="btn btn-edit"><i class="fas fa-edit"></i> Editar</a>
    <a asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>
</div>

BibliotecaWebApplication/BibliotecaWebApplication/Views/Libros/Index.cshtml
@model IEnumerable<BibliotecaWebApplication.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Libros</h1>

<p>
    <a asp-action="Create" class="btn btn-create"><i class="fas fa-plus"></i> Crear Libro</a>
</p>
<table id="dataTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroPaginas)
            </th>
            <th>Formato</th>
            <th>Autores</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroPaginas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Formato)
                </td>
                <td>
                    @foreach (var autorLibro in item.AutorLibros)
                    {
                        var autor = autorLibro.Autor;
                        <span>@autor.Nombres @autor.Apellidos</span>
                        <br />
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.LibroId" class="btn btn btn-edit btn-sm"><i class="fas fa-edit"></i> Editar</a>
                    <a asp-action="Details" asp-route-id="@item.LibroId" class="btn btn-details btn-sm"><i class="fas fa-info-circle"></i> Detalles</a>
                    <a asp-action="Delete" asp-route-id="@item.LibroId" class="btn btn btn-delete btn-sm"><i class="fas fa-trash-alt"></i> Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "lengthMenu": "Mostrar _MENU_ entradas por página",
                    "zeroRecords": "No se encontraron resultados",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                    "infoEmpty": "Mostrando 0 a 0 de 0 entradas",
                    "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}